# Generated by Django 4.2.21 on 2025-06-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insertion_membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_naissance', models.DateField()),
                ('passsword', models.CharField(max_length=100)),
                ('watsapp', models.IntegerField()),
                ('pays', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Insertion Membre',
                'verbose_name_plural': 'Insertions Membres',
            },
        ),
    ]
