# Generated by Django 4.2.21 on 2025-07-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insertion_membre',
            name='date_naissance',
        ),
        migrations.AddField(
            model_name='insertion_membre',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
