# Generated by Django 4.2.21 on 2025-07-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membre', '0002_remove_insertion_membre_date_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertion_membre',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insertion_membre',
            name='reset_token_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
