# Generated by Django 5.2.4 on 2025-07-03 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_accueil', '0001_initial'),
        ('app_membre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville_depart', models.CharField(max_length=100)),
                ('compagnie_vol', models.CharField(max_length=100)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_depart', models.DateTimeField()),
                ('nombre_personnes', models.PositiveIntegerField()),
                ('bagages', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='app_membre.insertion_membre')),
                ('taxi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='app_accueil.insertion_voiture')),
            ],
        ),
    ]
