# Generated by Django 5.2.4 on 2025-07-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='numero_reservation',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
