# Generated by Django 5.2.4 on 2025-07-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservation', '0002_reservation_numero_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date_depart',
            new_name='Heure_arriver',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='ville_depart',
            new_name='destination',
        ),
    ]
