# Generated by Django 4.2.21 on 2025-07-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservation', '0003_rename_date_depart_reservation_heure_arriver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='Heure_arriver',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_depart',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='ville_depart',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
