# Generated by Django 4.2.21 on 2025-07-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservation', '0004_remove_reservation_heure_arriver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
