# Generated by Django 4.2.21 on 2025-07-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservation', '0005_reservation_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
