# Generated by Django 4.2.21 on 2025-07-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservation', '0006_alter_reservation_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email_client',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
