# Generated by Django 5.1.4 on 2025-05-08 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insertion_voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('types', models.CharField(max_length=150)),
                ('marque', models.CharField(max_length=150)),
                ('disponibilite', models.BooleanField(default=True)),
                ('prix', models.FloatField()),
                ('photo', models.ImageField(upload_to='static/image')),
                ('photo2', models.ImageField(upload_to='static/image')),
                ('photo3', models.ImageField(upload_to='static/image')),
                ('photo4', models.ImageField(upload_to='static/image')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
