# Generated by Django 4.2.21 on 2025-07-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site_park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_park', models.CharField(max_length=250)),
                ('legende_park', models.CharField(max_length=250)),
                ('description_park', models.TextField()),
                ('detail', models.CharField(max_length=250)),
                ('photo1', models.ImageField(upload_to='static/image/site_voyage')),
                ('photo2', models.ImageField(upload_to='static/image/site_voyage')),
                ('photo3', models.ImageField(upload_to='static/image/site_voyage')),
                ('photo4', models.ImageField(upload_to='static/image/site_voyage')),
                ('photo5', models.ImageField(upload_to='static/image/site_voyage')),
                ('photo6', models.ImageField(upload_to='static/image/site_voyage')),
            ],
        ),
    ]
